name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --reporter mochawesome

      - name: Merge mochawesome reports
        run: npx mochawesome-merge cypress/reports/*.json -o cypress/reports/merged.json

      - name: Generate HTML report
        run: npx marge cypress/reports/merged.json -f index -o cypress/reports/html

      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-html
          path: cypress/reports/html

